### PR TITLE
Plant CI

### PR DESCRIPTION
**Pull request by lucafavatella**
In order to enable Travis CI, you need to follow https://docs.travis-ci.com/user/tutorial/#to-get-started-with-travis-ci

The CI content is taken from `tests/README.md`.

### CODE REVIEW

**Comment by lucafavatella** [comment]
Travis CI built this commit, with one failure. From https://travis-ci.org/github/lucafavatella/nix-androidenvtests/builds/661759664 the third job failed:
```
$ nix-build -A emulate_myfirstapp_debug.host_x86_64-linux.build_16.emulate_16.armeabi-v7a \
--arg useUpstream true

error: attribute 'emulate_16' in selection path 'emulate_myfirstapp_debug.host_x86_64-linux.build_16.emulate_16.armeabi-v7a' not found
The command "nix-build -A emulate_myfirstapp_debug.host_x86_64-linux.build_16.emulate_16.armeabi-v7a \
--arg useUpstream true
" exited with 1.
```

**Comment by lucafavatella** [comment]
Now the build example is fixed. But the emulator is slow to start hence CI fails.
CI build at https://travis-ci.org/github/lucafavatella/nix-androidenvtests/jobs/662124928

**Comment by lucafavatella** [comment]
Fixed CI by making emulator faster: https://travis-ci.org/github/lucafavatella/nix-androidenvtests/builds/662166433

**Comment by svanderburg** [comment]
Hi, great that you have worked on an automated CI solution.

However, there is one practical problem: we already had a CI solution for this project a couple of years ago (I ended up doing that on the Hydra instance of the Nix project).

Unfortunately, I removed it from Hydra for legal reasons: in order to use the Android SDK or any of its plugins, you must accept the Android EULA, a proprietary license, that covers the base SDK, but also most of its plugins.

Years ago, this was not a problem, because the SDK and most of its base plugins were much more liberally licensed -- the SDK, sources and platform SDKs were Apache licensed. Only some additional services, e.g. Google Play integration were properietary.

As a result of this license shift, I removed the test project from our publicly accessible Hydra servers and I have decided to do the testing privately on a non-public Hydra instance.

The only way to avoid this legal restriction is by compiling the SDK and the relevant base plugins from source code (because they are still governed by open source licenses), but that's something nobody has done so far for Nixpkgs. There can be instructions found online that can do it for Debian.

Sad conclusion, but yeah, we have to obtain the owners of the Android platform (you know to which company I'm referring to) with this choice of licensing.

**Comment by lucafavatella** [comment]
@svanderburg Thanks for the insight, very helpful. I am closing this PR then. I extracted the doc fix in #13 .

Hopefully I shall come back to these efforts in the following few days.

**Pull request closed without merging**
